spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #jdbc驱动
    url:  jdbc:mysql://localhost:3306/jianghong?useSSL=false #idbc 连接地址
    username: root #用户名
    password: jianghong #密码
    type: com.alibaba.druid.pool.DruidDataSource #连接池类型
    initialSize: 5 # 初始化连接池大小
    minIdle: 5  #最小活跃连接数
    maxActive: 20 #最大连接数
    maxWait: 60000 #获取连接最大等待时间，单位ms
    timeBetweenEvictionRunsMillis: 60000 #
    minEvictableIdleTimeMillis: 300000 #
    validationQuery: SELECT 1 FROM DUAL #
    testWhileIdle: true #
    testOnBorrow: false #
    testOnReturn: false #
    #
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j #
    useGlobalDataSourceStat: true #
  batch:
    job:
      enabled: false
  schema:
#debug: true
management:
  security:
    enabled: false
  info:
    git:
      mode: full